external/hunspell: Work around missing C++20 std::bit_cast
...as witnessed with <https://ci.libreoffice.org/job/gerrit_android_x86/31690/>
on top of patch set 4 of <https://gerrit.libreoffice.org/c/core/+/155121/4>
"Bump baseline to C++20",

> In file included from /home/tdf/lode/jenkins/workspace/android_x86/lingucomponent/source/spellcheck/spell/sspellimp.cxx:35:
> In file included from /home/tdf/lode/jenkins/workspace/android_x86/workdir/UnpackedTarball/hunspell/src/hunspell/hunspell.hxx:74:
> /home/tdf/lode/jenkins/workspace/android_x86/workdir/UnpackedTarball/hunspell/src/hunspell/w_char.hxx:62:17: error: no member named 'bit_cast' in namespace 'std'
>     return std::bit_cast<unsigned short>(*this);
>            ~~~~~^

Change-Id: Ic4a799a0918ff6bcc4dd414d5ae59e02181074bd
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/155346
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>